---
title: "Querying the gapminder"
author: "YOUR Name"
output: html_document
---

### Instructions
+ This homework is due on Tuesday July 26 by 11:59 pm. No late work is accepted unless prior arrangements have been made with the instructor.
+ Please answer ALL questions (including those that do not involve R) in the locations marked in this template. Remember to periodically **knit** your document to check that the output appears as you want it to; you will be turning in your knit html document. 
+ You will need to upload this document in CANVAS. Take a look at the material from Week 1: Hello World for instructions on exporting your files from JupyterHub and into CANVAS. 
+  Please answer the questions in the order in which they are posed. Write in complete sentences, and support your answers where asked. 



For this homework, we will continue querying the `gapminder` dataset we worked on in class.  Let's load the packages we need. 


```{r load-packages, include=FALSE}
library(tidyverse)    #umbrella package 
library(gapminder)       #for the data
```

## Exercises


### Exercise 1: Which country had the higher GDP per capita in 1977? United States or United Kingdom? Write code to print the rows for the U.S. and the U.K in 1977 and then answer the question in a complete sentence below your code chunk.


### Exercise 2: Which country in the Americas had the shortest life expectancy in the year 1962? Write code to print the row for this country. *Hint: use `arrange` and `slice_head` after creating the subset of data for the Americas in 1962. 


### Exercise 3: Create a new variable `log_pop` which is the natural logarithm of the population variable. Be sure to add the new variable to the `gapminder` data frame.


### Exercise 4: Pick a country (yes, your choice) and make a scatter plot of `log_pop` versus year for that country. 
